name = "cf-nav"
main = "worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "CARD_ORDER"
id = "890ee030176747179bfeb7e9ed332be0"
preview_id = ""

[vars]
ADMIN_PASSWORD = "you1987925"
